services:
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - .:/app
      - ./database/docker/nginx:/etc/nginx/conf.d:ro
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: database/docker/php/Dockerfile
    volumes:
      - .:/app
    depends_on:
      - mysql
      - mailhog

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"

  mysql:
    image: mariadb:11
    environment:
      MYSQL_DATABASE: developmentdb
      MYSQL_USER: developer
      MYSQL_PASSWORD: secret123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

volumes:
  dbdata:
