events {
    
}
http {
    include /etc/nginx/mime.types;
    server {
        listen 80 default_server;
        root /app/public;

        index index.php index.html index.htm;

        # uncomment line below to redirect all requests to index.php
        try_files $uri $uri/ /index.php?$args;

        location ~ \.php$ {
    try_files $uri =404;

    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_pass php:9000;

    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param SCRIPT_NAME $fastcgi_script_name;
}

    } 
}